# Generated by Django 5.2.2 on 2025-07-02 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('log_login_attempts', models.BooleanField(default=True, verbose_name='Registrar intentos de inicio de sesión')),
                ('log_data_access', models.BooleanField(default=True, verbose_name='Registrar acceso a datos')),
                ('log_data_changes', models.BooleanField(default=True, verbose_name='Registrar cambios en datos')),
                ('log_critical_operations', models.BooleanField(default=True, verbose_name='Registrar operaciones críticas')),
                ('retention_days', models.PositiveIntegerField(default=365, help_text='Número de días que se conservarán los registros antes de ser eliminados automáticamente', verbose_name='Días de retención')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_settings_updates', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración de auditoría',
                'verbose_name_plural': 'Configuraciones de auditoría',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('event_type', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('view', 'Visualización'), ('export', 'Exportación'), ('print', 'Impresión'), ('error', 'Error'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de evento')),
                ('object_category', models.CharField(choices=[('patient', 'Paciente'), ('doctor', 'Médico'), ('appointment', 'Cita'), ('prescription', 'Receta'), ('medical_record', 'Historial médico'), ('review', 'Reseña'), ('user', 'Usuario'), ('system', 'Sistema')], max_length=20, verbose_name='Categoría')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='ID del objeto')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Representación del objeto')),
                ('action', models.CharField(max_length=255, verbose_name='Acción')),
                ('details', models.TextField(blank=True, verbose_name='Detalles')),
                ('criticality', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Crítico')], default='info', max_length=10, verbose_name='Criticidad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx'), models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'), models.Index(fields=['event_type'], name='audit_audit_event_t_4496ba_idx'), models.Index(fields=['object_category'], name='audit_audit_object__e4569a_idx'), models.Index(fields=['criticality'], name='audit_audit_critica_101ced_idx')],
            },
        ),
    ]
