# Generated by Django 5.2.2 on 2025-07-04 05:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
            options={
                'verbose_name': 'Rango de tiempo',
                'verbose_name_plural': 'Rangos de tiempo',
            },
        ),
    ]
