# Generated by Django 5.2.2 on 2025-07-01 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_alter_booking_options_booking_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_before', models.PositiveIntegerField(default=24, help_text='Horas antes de la cita para enviar el recordatorio')),
                ('enabled', models.BooleanField(default=True)),
                ('email_subject', models.CharField(default='Recordatorio de cita médica', max_length=255)),
                ('email_template_patient', models.TextField(default='Estimado/a {patient_name},\n\nLe recordamos que tiene una cita programada con el Dr. {doctor_name} el {appointment_date} a las {appointment_time}.\n\nPor favor, llegue con 10 minutos de anticipación.\n\nAtentamente,\nEquipo Médico')),
                ('email_template_doctor', models.TextField(default='Estimado/a Dr. {doctor_name},\n\nLe recordamos que tiene una cita programada con el paciente {patient_name} el {appointment_date} a las {appointment_time}.\n\nAtentamente,\nEquipo Médico')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de recordatorios',
                'verbose_name_plural': 'Configuraciones de recordatorios',
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to_patient', models.BooleanField(default=False)),
                ('sent_to_doctor', models.BooleanField(default=False)),
                ('patient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('doctor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Registro de recordatorio',
                'verbose_name_plural': 'Registro de recordatorios',
            },
        ),
        migrations.CreateModel(
            name='UserReminderPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('hours_before', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de recordatorio',
                'verbose_name_plural': 'Preferencias de recordatorios',
            },
        ),
    ]
