# Generated by Django 5.2.2 on 2025-07-01 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True, help_text='Liste todas las alergias conocidas', verbose_name='Alergias')),
                ('medications', models.TextField(blank=True, help_text='Liste los medicamentos que está tomando actualmente', verbose_name='Medicamentos actuales')),
                ('chronic_diseases', models.TextField(blank=True, help_text='Liste las enfermedades crónicas diagnosticadas', verbose_name='Enfermedades crónicas')),
                ('previous_surgeries', models.TextField(blank=True, help_text='Liste las cirugías previas con fechas aproximadas', verbose_name='Cirugías previas')),
                ('family_history', models.TextField(blank=True, help_text='Historial médico familiar relevante', verbose_name='Antecedentes familiares')),
                ('blood_type', models.CharField(blank=True, max_length=10, verbose_name='Grupo sanguíneo')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_records', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Historial médico',
                'verbose_name_plural': 'Historiales médicos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=255, verbose_name='Diagnóstico')),
                ('diagnosis_date', models.DateField(verbose_name='Fecha de diagnóstico')),
                ('treatment', models.TextField(blank=True, verbose_name='Tratamiento')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_diagnoses', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients.medicalrecord', verbose_name='Historial médico')),
            ],
            options={
                'verbose_name': 'Diagnóstico médico',
                'verbose_name_plural': 'Diagnósticos médicos',
                'ordering': ['-diagnosis_date'],
            },
        ),
    ]
