# Generated by Django 5.2.2 on 2025-07-03 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_booking_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto pagado'),
        ),
        migrations.AddField(
            model_name='booking',
            name='consultation_type',
            field=models.CharField(choices=[('normal', 'Consulta General'), ('specialty', 'Consulta por Especialidad')], default='normal', max_length=20, verbose_name='Tipo de consulta'),
        ),
        migrations.AddField(
            model_name='booking',
            name='medical_history_file',
            field=models.FileField(blank=True, null=True, upload_to='medical_histories/', verbose_name='Archivo de historial médico'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.BooleanField(default=False, verbose_name='Estado de pago'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
